security:
  jwt:
    header: X-Authorization
    prefix: "Bearer "
    expiration: 86400000
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 28688220974-48vkli2fb06nnrcorf4amh077gqnqr0p.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  flyway:
    enabled: false
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/pamiw}
    username: ${DATASOURCE_USERNAME:pamiw}
    password: ${DATASOURCE_PASSWORD:pamiw}
  docker:
    compose:
      enabled: false
  devtools:
    add-properties: false